# Default configuration for Document Management Platform
# This file contains base settings that can be overridden by environment-specific configurations

# Environment identifier
environment: default

# HTTP Server configuration
server:
  host: 0.0.0.0
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  tls: false
  cert_file: ./certs/server.crt
  key_file: ./certs/server.key

# Logging configuration
log:
  level: info
  format: json
  output: stdout
  enable_console: true
  enable_file: false
  file_path: ./logs/app.log

# Database configuration (PostgreSQL)
database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: document_mgmt
  sslmode: disable
  max_open_conns: 20
  max_idle_conns: 10
  conn_max_lifetime: 1h

# Storage configuration (AWS S3)
storage:
  region: us-east-1
  endpoint: ""
  access_key: ""
  secret_key: ""
  bucket: document-mgmt-docs
  temp_bucket: document-mgmt-temp
  quarantine_bucket: document-mgmt-quarantine
  use_ssl: true
  force_path_style: false

# Elasticsearch configuration
elasticsearch:
  addresses:
    - http://localhost:9200
  username: ""
  password: ""
  enable_sniff: true
  index_prefix: documents

# JWT Authentication configuration
jwt:
  secret: changeme
  public_key: ./keys/jwt_public.pem
  private_key: ./keys/jwt_private.pem
  issuer: document-mgmt
  expiration_time: 24h
  algorithm: RS256

# ClamAV virus scanning configuration
clamav:
  host: localhost
  port: 3310
  timeout: 60

# AWS SQS configuration
sqs:
  region: us-east-1
  endpoint: ""
  access_key: ""
  secret_key: ""
  document_queue_url: https://sqs.us-east-1.amazonaws.com/account-id/document-queue
  scan_queue_url: https://sqs.us-east-1.amazonaws.com/account-id/scan-queue
  index_queue_url: https://sqs.us-east-1.amazonaws.com/account-id/index-queue
  use_ssl: true

# AWS SNS configuration
sns:
  region: us-east-1
  endpoint: ""
  access_key: ""
  secret_key: ""
  document_topic_arn: arn:aws:sns:us-east-1:account-id:document-topic
  event_topic_arn: arn:aws:sns:us-east-1:account-id:event-topic
  use_ssl: true

# Redis caching configuration
redis:
  address: localhost:6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

# API rate limiting
rate_limiter:
  enabled: true
  requests_per_minute: 100
  burst_size: 150

# CORS configuration
cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Authorization
    - Content-Type
    - X-Requested-With
  exposed_headers:
    - Content-Length
    - Content-Type
    - X-Request-ID
  allow_credentials: true
  max_age: 86400

# Metrics configuration
metrics:
  enabled: true
  endpoint: /metrics
  namespace: document_mgmt

# Distributed tracing configuration
tracing:
  enabled: true
  provider: jaeger
  endpoint: http://localhost:14268/api/traces
  service_name: document-mgmt
  sample_rate: 0.1

# Document limits
document_limits:
  max_file_size: 104857600  # 100MB in bytes
  allowed_mime_types:
    - application/pdf
    - application/msword
    - application/vnd.openxmlformats-officedocument.wordprocessingml.document
    - application/vnd.ms-excel
    - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
    - application/vnd.ms-powerpoint
    - application/vnd.openxmlformats-officedocument.presentationml.presentation
    - image/jpeg
    - image/png
    - image/gif
    - image/tiff
    - text/plain
    - text/csv
    - application/rtf
    - application/json
    - application/xml
    - application/zip
    - application/x-rar-compressed
    - application/x-tar
    - application/gzip
  max_batch_size: 10