apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-collector
  namespace: monitoring
  annotations:
    kubernetes.io/description: "Jaeger Collector deployment for distributed tracing in Document Management Platform"
  labels:
    app: jaeger
    component: collector
    part-of: document-management-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jaeger
      component: collector
  template:
    metadata:
      labels:
        app: jaeger
        component: collector
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "14268"
    spec:
      serviceAccountName: jaeger
      containers:
      - name: jaeger-collector
        image: jaegertracing/jaeger-collector:1.38.0
        ports:
        - containerPort: 14250
          name: grpc
        - containerPort: 14268
          name: http
        - containerPort: 9411
          name: zipkin
        env:
        - name: SPAN_STORAGE_TYPE
          value: "elasticsearch"
        - name: ES_SERVER_URLS
          value: "http://elasticsearch:9200"
        - name: ES_USERNAME
          valueFrom:
            secretKeyRef:
              name: jaeger-elasticsearch-credentials
              key: username
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jaeger-elasticsearch-credentials
              key: password
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: ":9411"
        - name: COLLECTOR_QUEUE_SIZE
          value: "1000"
        - name: COLLECTOR_NUM_WORKERS
          value: "50"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: jaeger-config-volume
          mountPath: /etc/jaeger
          readOnly: true
        livenessProbe:
          httpGet:
            path: /
            port: 14268
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 14268
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: jaeger-config-volume
        configMap:
          name: jaeger-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-query
  namespace: monitoring
  annotations:
    kubernetes.io/description: "Jaeger Query deployment for distributed tracing in Document Management Platform"
  labels:
    app: jaeger
    component: query
    part-of: document-management-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jaeger
      component: query
  template:
    metadata:
      labels:
        app: jaeger
        component: query
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "16686"
    spec:
      serviceAccountName: jaeger
      containers:
      - name: jaeger-query
        image: jaegertracing/jaeger-query:1.38.0
        ports:
        - containerPort: 16686
          name: http
        env:
        - name: SPAN_STORAGE_TYPE
          value: "elasticsearch"
        - name: ES_SERVER_URLS
          value: "http://elasticsearch:9200"
        - name: ES_USERNAME
          valueFrom:
            secretKeyRef:
              name: jaeger-elasticsearch-credentials
              key: username
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jaeger-elasticsearch-credentials
              key: password
        - name: QUERY_BASE_PATH
          value: "/jaeger"
        - name: QUERY_UI_CONFIG
          value: "/etc/jaeger/ui-config.json"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: jaeger-config-volume
          mountPath: /etc/jaeger
          readOnly: true
        readinessProbe:
          httpGet:
            path: /
            port: 16686
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 16686
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: jaeger-config-volume
        configMap:
          name: jaeger-config