apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: monitoring
  annotations:
    kubernetes.io/description: "Jaeger Collector service for distributed tracing in Document Management Platform"
    prometheus.io/scrape: "true"
    prometheus.io/port: "14268"
  labels:
    app: jaeger
    component: collector
    part-of: document-management-platform
spec:
  selector:
    app: jaeger
    component: collector
  ports:
    - name: grpc
      port: 14250
      targetPort: 14250
      protocol: TCP
    - name: http
      port: 14268
      targetPort: 14268
      protocol: TCP
    - name: zipkin
      port: 9411
      targetPort: 9411
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: monitoring
  annotations:
    kubernetes.io/description: "Jaeger Query service for distributed tracing in Document Management Platform"
    prometheus.io/scrape: "true"
    prometheus.io/port: "16686"
  labels:
    app: jaeger
    component: query
    part-of: document-management-platform
spec:
  selector:
    app: jaeger
    component: query
  ports:
    - name: http
      port: 16686
      targetPort: 16686
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: monitoring
  annotations:
    kubernetes.io/description: "Jaeger Agent service for distributed tracing in Document Management Platform"
    prometheus.io/scrape: "true"
    prometheus.io/port: "5778"
  labels:
    app: jaeger
    component: agent
    part-of: document-management-platform
spec:
  selector:
    app: jaeger
    component: agent
  ports:
    - name: zipkin-compact
      port: 5775
      targetPort: 5775
      protocol: UDP
    - name: thrift-compact
      port: 6831
      targetPort: 6831
      protocol: UDP
    - name: thrift-binary
      port: 6832
      targetPort: 6832
      protocol: UDP
    - name: config-rest
      port: 5778
      targetPort: 5778
      protocol: TCP
  type: ClusterIP