apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: monitoring
  annotations:
    kubernetes.io/description: "Kibana service for Document Management Platform monitoring"
    prometheus.io/scrape: "true"
    prometheus.io/port: "5601"
    prometheus.io/path: "/api/status"
  labels:
    app: kibana
    component: monitoring
    part-of: document-management-platform
spec:
  type: ClusterIP
  selector:
    app: kibana
  ports:
    - name: http
      port: 5601
      targetPort: 5601
      protocol: TCP
  sessionAffinity: None