apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: document-management
    part-of: document-platform
  annotations:
    kubernetes.io/description: "Configuration for Document Management Platform"
data:
  aws-region: "us-east-1"
  s3-temp-bucket: "document-mgmt-temp"
  s3-permanent-bucket: "document-mgmt-permanent"
  s3-quarantine-bucket: "document-mgmt-quarantine"
  elasticsearch-addresses: "http://elasticsearch-service:9200"
  clamav-endpoint: "http://clamav-service:3310"
  sqs-document-queue: "https://sqs.us-east-1.amazonaws.com/123456789012/document-processing-queue"
  sqs-scan-queue: "https://sqs.us-east-1.amazonaws.com/123456789012/virus-scan-queue"
  sqs-index-queue: "https://sqs.us-east-1.amazonaws.com/123456789012/document-indexing-queue"
  sns-document-topic: "arn:aws:sns:us-east-1:123456789012:document-events"
  sns-event-topic: "arn:aws:sns:us-east-1:123456789012:platform-events"
  redis-address: "redis-service:6379"
  log-level: "info"
  max-file-size: "104857600"
  allowed-mime-types: "application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation,image/jpeg,image/png,image/gif,image/tiff,text/plain,text/csv,application/json,application/xml"
  max-batch-size: "10"
  production.yml: |
    environment: production
    server:
      host: 0.0.0.0
      port: 8080
      read_timeout: 30s
      write_timeout: 30s
      idle_timeout: 120s
      tls: false
    log:
      level: info
      format: json
      output: stdout
      enable_console: true
      enable_file: false
    document_limits:
      max_file_size: 104857600
      allowed_mime_types:
        - application/pdf
        - application/msword
        - application/vnd.openxmlformats-officedocument.wordprocessingml.document
        - application/vnd.ms-excel
        - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
        - application/vnd.ms-powerpoint
        - application/vnd.openxmlformats-officedocument.presentationml.presentation
        - image/jpeg
        - image/png
        - image/gif
        - image/tiff
        - text/plain
        - text/csv
        - application/json
        - application/xml
      max_batch_size: 10
    rate_limiter:
      enabled: true
      requests_per_minute: 100
      burst_size: 150
    cors:
      allowed_origins:
        - '*'
      allowed_methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed_headers:
        - Authorization
        - Content-Type
        - X-Tenant-ID
      exposed_headers:
        - X-Request-ID
      allow_credentials: false
      max_age: 86400
    metrics:
      enabled: true
      endpoint: /metrics
      namespace: document_platform
    tracing:
      enabled: true
      provider: jaeger
      endpoint: http://jaeger-collector:14268/api/traces
      service_name: document-platform
      sample_rate: 0.1