apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: document-processing-pvc
  labels:
    app: document-management
    component: storage
    part-of: document-platform
  annotations:
    kubernetes.io/description: "Persistent storage for document processing operations"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virus-scanning-pvc
  labels:
    app: document-management
    component: storage
    part-of: document-platform
  annotations:
    kubernetes.io/description: "Persistent storage for virus scanning operations"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thumbnail-processing-pvc
  labels:
    app: document-management
    component: storage
    part-of: document-platform
  annotations:
    kubernetes.io/description: "Persistent storage for thumbnail generation operations"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard