apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app: document-management
    part-of: document-platform
  annotations:
    kubernetes.io/description: "Sensitive configuration for Document Management Platform"
type: Opaque
data:
  db-host: "Base64-encoded PostgreSQL host"
  db-port: "Base64-encoded PostgreSQL port"
  db-username: "Base64-encoded PostgreSQL username"
  db-password: "Base64-encoded PostgreSQL password"
  db-name: "Base64-encoded PostgreSQL database name"
  aws-access-key: "Base64-encoded AWS access key"
  aws-secret-key: "Base64-encoded AWS secret key"
  elasticsearch-username: "Base64-encoded Elasticsearch username"
  elasticsearch-password: "Base64-encoded Elasticsearch password"
  jwt-secret: "Base64-encoded JWT signing secret"
  redis-password: "Base64-encoded Redis password"